services:
  captive-portal:
    build:
      context: .
      args:
        SESSION_SECRET: ${SESSION_SECRET}
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: "80"
    container_name: captive-portal
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE
    env_file:
      - .env
    volumes:
      - db-data:/app/prisma

volumes:
  db-data:
